src/main/java/org/springframework/samples/petclinic/model/Vet.java
/*
 * Copyright 2002-2013 the original author or authors.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package org.springframework.samples.petclinic.model;

import java.util.HashSet;
import java.util.Set;

import javax.persistence.CascadeType;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.JoinTable;
import javax.persistence.ManyToMany;
import javax.persistence.Table;

/**
 * Simple JavaBean domain object representing a veterinarian.
 *
 * @author Ken Krebs
 * @author Juergen Hoeller
 * @author Sam Brannen
 * @author Arjen Poutsma
 */
@Entity
@Table(name = "vets")
public class Vet extends Person {

    @ManyToMany(cascade={CascadeType.MERGE, CascadeType.REFRESH},fetch = FetchType.EAGER)
    @JoinTable(name = "vet_specialties", joinColumns = @JoinColumn(name = "vet_id"),
            inverseJoinColumns = @JoinColumn(name = "specialty_id"))
    private Set<Specialty> specialties;


    protected void setSpecialtiesInternal(Set<Specialty> specialties) {
        this.specialties = specialties;
    }

    public void setSpecialties(Set<Specialty> specialties) {
		this.specialties = specialties;
	}

	protected Set<Specialty> getSpecialtiesInternal() {
        if (this.specialties == null) {
            this.specialties = new HashSet<Specialty>();
        }
        return this.specialties;
    }

//    @XmlElement
//    public List<Specialty> getSpecialties() {
//        List<Specialty> sortedSpecs = new ArrayList<Specialty>(getSpecialtiesInternal());
//        PropertyComparator.sort(sortedSpecs, new MutableSortDefinition("name", true, true));
//        return Collections.unmodifiableList(sortedSpecs);
//    }

    public int getNrOfSpecialties() {
        return getSpecialtiesInternal().size();
    }

    public Set<Specialty> getSpecialties() {
		return specialties;
	}

	public void addSpecialty(Specialty specialty) {
        getSpecialtiesInternal().add(specialty);
    }

}

src/main/java/org/springframework/samples/petclinic/model/Vets.java
/*
/*
 * Copyright 2002-2013 the original author or authors.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package org.springframework.samples.petclinic.model;

import java.util.ArrayList;
import java.util.List;

import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;

/**
 * Simple domain object representing a list of veterinarians. Mostly here to be used for the 'vets' {@link
 * org.springframework.web.servlet.view.xml.MarshallingView}.
 *
 * @author Arjen Poutsma
 */
@XmlRootElement
public class Vets {

    private List<Vet> vets;

    @XmlElement
    public List<Vet> getVetList() {
        if (vets == null) {
            vets = new ArrayList<Vet>();
        }
        return vets;
    }

}

src/main/java/org/springframework/samples/petclinic/web/VetController.java
/*
 * Copyright 2002-2013 the original author or authors.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package org.springframework.samples.petclinic.web;

import java.lang.reflect.Method;
import java.util.ArrayList;
import java.util.Collection;
import java.util.Collections;
import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

import javax.validation.Valid;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.samples.petclinic.model.Pet;
import org.springframework.samples.petclinic.model.Specialty;
import org.springframework.samples.petclinic.model.Vet;
import org.springframework.samples.petclinic.model.Vets;
import org.springframework.samples.petclinic.service.ClinicService;
import org.springframework.stereotype.Controller;
import org.springframework.validation.BindingResult;
import org.springframework.web.bind.annotation.ModelAttribute;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;
import org.springframework.web.bind.support.SessionStatus;

/**
 * @author Juergen Hoeller
 * @author Mark Fisher
 * @author Ken Krebs
 * @author Arjen Poutsma
 */
@Controller
public class VetController {

	private final ClinicService clinicService;

	@Autowired
	public VetController(ClinicService clinicService) {
		this.clinicService = clinicService;
	}
	
	@ModelAttribute(value="specialities")
	public List<Specialty> getSpeciality(){
		return this.clinicService.findSpecialities();
	}

	@RequestMapping("/vets")
	public String showVetList(Map<String, Object> model) {
		// Here we are returning an object of type 'Vets' rather than a
		// collection of Vet objects
		// so it is simpler for Object-Xml mapping
		Vets vets = new Vets();
		
		Collection<Vet> listVets = new ArrayList<Vet>();
		listVets = this.clinicService.findVets();
		
		vets.getVetList().addAll(listVets);
		model.put("vets", vets);
		return "vets/vetList";
	}

	@RequestMapping(value = "/vets/new", method = RequestMethod.GET)
	public String vetForm(Map<String, Object> model) {
		Vet vet = new Vet();
		model.put("vet", vet);

		return "vets/createOrUpdateVetForm";
	}
	
	@RequestMapping(value = "/vets/new", method = RequestMethod.POST)
	public String vetSave(@Valid Vet vet, BindingResult result, SessionStatus status) {
		
		if(result.hasErrors()){
			return "vets/createOrUpdateVetForm";
		}
		clinicService.saveVet(vet);
		status.setComplete();
		return "redirect:/vets.html";
	}
	
    @RequestMapping(value = "/vet/{id}/delete", method = {RequestMethod.GET})
    public String deleteVet(@PathVariable("id") int id, SessionStatus status) {
    	
    	clinicService.deleteVetAllSpecialty(id);

    	clinicService.deleteVet(id);
    	
    	status.setComplete();
    	
    	return "redirect:/vets.html";
    }
    
    @RequestMapping(value = "/vet/{id}/edit", method = {RequestMethod.GET})
    public String editVetForm(@PathVariable("id") int id, Map<String, Object> model) {
    	
    	Vet vet = clinicService.findVetByID(id);
    	model.put("vet", vet);
    	
    	return "vets/createOrUpdateVetForm";
    }
    
	@RequestMapping(value = "/vet/{id}/edit", method = RequestMethod.POST)
	public String editVet(@Valid Vet vet, BindingResult result, SessionStatus status) {
		
		if(result.hasErrors()){
			return "vets/createOrUpdateVetForm";
		}
		clinicService.saveVet(vet);
		status.setComplete();
		return "redirect:/vets.html";
	}
	
    @RequestMapping(value = "/vet/specialty/{vetId}/{specialtyId}/delete", method = {RequestMethod.GET})
    public String deleteVetSpecialtyByID(@PathVariable("vetId") int vetId,
    		@PathVariable("specialtyId") int specialtyId, SessionStatus status) {
    	
    	Vet vet = clinicService.findVetByID(vetId);
    	Set<Specialty> specialties = vet.getSpecialties();
    	
    	for(Specialty specialty : specialties){
    		if(specialtyId == specialty.getId()){
    			specialties.remove(specialty);
    		}
    	}
    	
    	vet.setSpecialties(specialties);
    	clinicService.saveVet(vet);
    	
    	status.setComplete();
    	
    	return "redirect:/vets.html";
    }

}

src/main/webapp/WEB-INF/jsp/vets/createOrUpdateVetForm.jsp
<%@page import="java.io.File"%>
<!DOCTYPE html> 

<%@ taglib prefix="spring" uri="http://www.springframework.org/tags" %>
<%@ taglib prefix="fmt" uri="http://java.sun.com/jsp/jstl/fmt" %>
<%@ taglib prefix="c" uri="http://java.sun.com/jsp/jstl/core" %>
<%@ taglib prefix="fn" uri="http://java.sun.com/jsp/jstl/functions" %>
<%@ taglib prefix="form" uri="http://www.springframework.org/tags/form" %>
<%@ taglib prefix="petclinic" tagdir="/WEB-INF/tags" %>


<html lang="en">

    <jsp:include page="../fragments/headTag.jsp"/>

<script type="text/javascript">
		$(document).ready(function() {
			
			$('#submit').click(function(event) {
	
				var multiSelect = $('select#specialities').val();
				$('select#specialities').find('option').removeAttr("selected");
				alert(multiSelect);
				$('select#specialities').append("<option selected='selected' class='hidden' value=" + multiSelect + ">added</option>");
			});
			
		});
    </script>

	<style>
		.hidden {
			visibility: hidden;
		}
		
	</style>


<body>
        <div class="container">
            <jsp:include page="../fragments/bodyHeader.jsp"/>
            <c:choose>
                <c:when test="${vet['new']}"><c:set var="method" value="post"/></c:when>
                <c:otherwise><c:set var="method" value="post"/></c:otherwise>
            </c:choose>

            <h2>
                <c:if test="${vet['new']}">New </c:if> Vet
                </h2>

            <form:form modelAttribute="vet" method="${method}" 
                       class="form-horizontal" id="add-vet-form"
                       enctype="multipart/form-data">

                <petclinic:inputField label="First Name" name="firstName"/>
                <petclinic:inputField label="Last Name" name="lastName"/>
                
                <div class="control-group ">
                	<label class="control-label">Speciality In :</label>
                <!--  	<form:select path="specialties" multiple="true" items="${specialities}" itemValue="id" itemLabel="name"/> -->
					
				<form:select path="specialties" multiple="true" id="specialities">
                    <form:options items="${specialities}" itemValue="id" itemLabel="name" />
                </form:select>
					
					<form:errors path="specialties" />
				</div>
				
                <div class="form-actions">
                    <c:choose>
                        <c:when test="${vet['new']}">
                            <button type="submit" id="submit">Add Vet</button>
                        </c:when>
                        <c:otherwise>
                            <button type="submit" id="submit">Update Vet</button>
                        </c:otherwise>
                    </c:choose>
                </div>

            </form:form>
        </div>
        <jsp:include page="../fragments/footer.jsp"/>
    </body>

</html>

src/main/webapp/WEB-INF/jsp/vets/vetList.jsp
<!DOCTYPE html> 

<%@ taglib prefix="spring" uri="http://www.springframework.org/tags" %>
<%@ taglib prefix="fmt" uri="http://java.sun.com/jsp/jstl/fmt" %>
<%@ taglib prefix="c" uri="http://java.sun.com/jsp/jstl/core" %>
<%@ taglib prefix="datatables" uri="http://github.com/dandelion/datatables" %>

<html lang="en">


<jsp:include page="../fragments/headTag.jsp"/>

<body>

<spring:url value="/resources/images/delete.png" var="delete" />
<spring:url value="/resources/images/delete-small.png" var="delete_small" />
<spring:url value="/resources/images/edit.png" var="edit" />

<div class="container">
    <jsp:include page="../fragments/bodyHeader.jsp"/>

    <h2>Veterinarians</h2>

    <datatables:table id="vets" data="${vets.vetList}" cdn="true" row="vet" theme="bootstrap2" cssClass="table table-striped" paginate="false" info="false">
        <datatables:column title="Name">
        
        	<spring:url value="/vet/${vet.id}/delete" var="deleteVet" />
        	<a href="${deleteVet}"><img alt="delete" src="${delete}" /></a>
        	
        	<spring:url value="/vet/${vet.id}/edit" var="editVet" />
        	<a href="${editVet}"><img alt="edit" src="${edit}" /></a>
        	&nbsp;&nbsp;
        	
            <c:out value="${vet.firstName} ${vet.lastName}"></c:out>
        </datatables:column>
        
        <datatables:column title="Specialties">
            <c:forEach var="specialty" items="${vet.specialties}">
            
            	<!-- Add delete functionality -->
            	<spring:url value="/vet/specialty/${vet.id}/${specialty.id}/delete" var="deleteSpecialty" />
            	<a href="${deleteSpecialty}"><img src="${delete_small}" alt="delete_specialty" /></a>
            
                <c:out value="${specialty.name}"/>
     
            </c:forEach>
            <c:if test="${vet.nrOfSpecialties == 0}">none</c:if>
        </datatables:column>
        
    </datatables:table>
    
    	<br /> 
	<a href='<spring:url value="/vets/new" htmlEscape="true"/>'>Add	Vet</a>
    
    <table class="table-buttons">
        <tr>
            <td>
                <a href="<spring:url value="/vets.xml" htmlEscape="true" />">View as XML</a>
            </td>
            <td>
                <a href="<spring:url value="/vets.atom" htmlEscape="true" />">Subscribe to Atom feed</a>
            </td>
        </tr>
    </table>

		<jsp:include page="../fragments/footer.jsp"/>
</div>
</body>

</html>